import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
// import Navbar from "./_components/navbar";


const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ranah",
  description: "Generated by create next app",
};

export default function Layout({children} : {children: React.ReactNode}) {
  return (
    <html lang="en" className={nunito.className}>
    <body>
      {children}
    </body>
  </html>
  );
}

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" className={nunito.className}>
//       <body>
//         <Navbar />
//         <main>{children}</main>
//       </body>
//     </html>
//   );
// }
