import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import Sidebar from "../_components/sidebar";


const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ranah",
  description: "Generated by create next app",
};

export default function RootLayout({children} : {children: React.ReactNode}) {
  return (
    <html lang="en" className={nunito.className}>
    <body>
        <div>
            <Sidebar />
            {children}
        </div>
    </body>
  </html>
  );
}
